# Sponsorship Configuration
# This file defines funding options for the project
# See: https://docs.github.com/articles/displaying-a-sponsor-button-in-your-repository

# GitHub Sponsors
github: [NormB]

# Patreon
# patreon: your-patreon-username

# Open Collective
# open_collective: your-opencollective-username

# Buy Me A Coffee
# buy_me_a_coffee: your-buymeacoffee-username

# Tidelift
# tidelift: npm/package-name

# Community Bridge
# community_bridge: project-name

# Liberapay
# liberapay: your-liberapay-username

# IssueHunt
# issuehunt: your-issuehunt-username

# Otechie
# otechie: your-otechie-username

# LFX Crowdfunding
# lfx_crowdfunding: project-name

# Custom URLs (max 4)
# custom: ['https://www.paypal.me/username', 'https://example.com/donate']
